### PR TITLE
Add ability to log attachments in database

### LINKED ISSUE #35: Attachments and html message are not saved to logs
The problem is when I send messages with a file and/or `html_message`, they are not saved to the database.

### PR DESCRIPTION
**Pull request by vanya909**
New model for attachments was created.

Also new field `html_message` was added to `Email` model.

Tests were provided.

Also, I've deleted `insert_final_newline` from `.editorconfig` because I've got some problems with linters when it was enabled.

And I've changed `.pre-commit-config.yaml` a little bit because there are problems with old version of linters.

Attempt to fix #35 issue

### CODE REVIEW

**Comment by spapas** [comment]
Hello @vanya909 I'd like to ask you if there's a way to configure the attachment saving or not ? I undestand that this may be useful in some situations however I definitely wouldn't like the email attachments to be saved as files ...

Two solutions for this would be to add a 2nd backend that would save the email attachments (i.e `EmailAttachmentsBackend`) or maybe add a `EMAIL_LOG_SAVE_ATTACHMENTS` django setting (but this setting must be False by default so the behavior won't be changed).

**Comment by vanya909** [comment]
@spapas thank you for the answer. I agree, ability to configure behavior is important and solution with `django setting` sound more applicable for me.
I'm going to implement this right away.
Also, should I add same setting for `html message` or it is ok to save it in the database always?

**Comment by spapas** [comment]
Hello @vanya909 thank you!

I am neutral on the issue of whether to always save HTML messages or make it configurable. Perhaps @treyhunner could provide their thoughts on the matter.

**Comment by spapas** [comment]
Also please take a peek at #37, the tests won't run until we fix the python 3.6 problem.

**Comment by spapas** [comment]
Hello @vanya909 could you please merge main now that #37 has been resolved to try running the tests again ?

Thank you

**Comment by vanya909** [comment]
@spapas Done, I've rebased the branch

**Comment by spapas** [comment]
@vanya909 hello it seems that all tests are passing now however for reasons unknown to me ti expects the build 3.6 to be run although it has been removed here https://github.com/treyhunner/django-email-log/pull/39. 

I thought that since we have merged #39 to main it wouldn't still require the python 3.6 test to pass! Do you maybe have any idea what's the problem ?

**Comment by vanya909** [comment]
Hello @spapas! I don't know the reason for such behavior to be honest. But I think it might be because it's PR from forked repo and in mine repo still python 3.6 is presented. Should I fork and open PR again or what do I do?

**Comment by spapas** [comment]
Hello @vanya909 unfortunately I can't merge the changes unless all tests pass.

@treyhunner can you please take a peek at this pr? Thank you

**Comment by spapas** [comment]
Hello @treyhunner, no problem I think everything's fine! 

However I'll test it a bit more next week and if everything's cool I'll prepare a new pypi release (1.3).

Kind regards,
Serafeim

**Pull request merged**
