### PR TITLE
Update apps.py to set default_auto_field (fixes #23)

### LINKED ISSUE #23: Please define the `default_auto_field` in your apps.py
Since djago 3.2 it is required to configure the type of the auto generated id field of your models. Most people will usually just add a global DEFAULT_AUTO_FIELD setting. 

This is problematic because for projects that have a `DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'` a nasty migration will be generated that will convert the django-email-log id to `BigAutoField`. 

The solution is to just add default_auto_field = "django.db.models.AutoField" in your apps.py. I'll add a quick PR with with that fix exactly. 

Thank you

### PR DESCRIPTION
**Pull request by spapas**

### CODE REVIEW

**Comment by treyhunner** [comment]
@spapas do you think we should add a test to make sure there aren't warnings (which is what this fixes at the moment)?

I'm also fine merging this as-is and either making a warnings test later or just manually fixing warnings after we run tests.

**Comment by spapas** [comment]
Hello @treyhunner I've added a test that makes sure that the W042 warning (the one that was displayed) is not displayed anymore after we add the `default_auto_field ` attribute in apps.py. I think we can now merge this PR if you agree!

**Comment by treyhunner** [comment]
Hey @spapas. I do think it's good to merge.

I was actually thinking of a more broad catch-all "make sure no warnings at all occur" test (which would fail pretty often for example when testing against a new Django version that has deprecations we're using).

We could leave a test like that for later though (since it is a bit outside the scope of this PR). But I am curious to hear what you think about going broad in validating there are 0 warnings (rather than checking for individual warnings).

**Comment by spapas** [comment]
It would be nice to go the 0 warning path but if you run the tests now you'll see that there's already a warning `?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.` that isn't really related to email-log.  

I presume it will be fixed if we added the `django.template.context_processors.request` context processor to our tests settings? I'll try it and if it's ok then I'll add another PR with a 0 warning check.

**Comment by treyhunner** [comment]
> It would be nice to go the 0 warning path but if you run the tests now you'll see that there's already a warning `?: (admin.W411) 'django.template.context_processors.request' must be enabled in DjangoTemplates (TEMPLATES) in order to use the admin navigation sidebar.` that isn't really related to email-log.
> 
> I presume it will be fixed if we added the `django.template.context_processors.request` context processor to our tests settings? I'll try it and if it's ok then I'll add another PR with a 0 warning check.

Ah yes that is a downside (testing our test settings rather than the app). Hopefully adding that to the settings will fix it.

**Comment by spapas** [comment]
Yes it does fix it :) https://github.com/treyhunner/django-email-log/pull/29

**Pull request merged**
