### PR TITLE
Remove python 3.6

### PR DESCRIPTION
**Pull request by spapas**

### CODE REVIEW

**Comment by spapas** [comment]
Hello @treyhunner this should be ready to fix #37. Two small things:

- I changed the flake8 repo from gitlab to github because the gitlab was throwing an error for some reason
- It seems to expect "the python 3.6" (see the "Some tests have not completed yet section) althrough I have removed it from everywhere ! I'm really not sure where it picks that :|

**Review by treyhunner — APPROVED** [review]
Thanks @spapas! 😁

> * It seems to expect "the python 3.6" (see the "Some tests have not completed yet section) althrough I have removed it from everywhere ! I'm really not sure where it picks that :|

I don't understand where it's getting that from either... hopefully it's just taking it from the `main` branch, which will update once this PR is merged.

This looks great to me! 👍 Let's merge it. 🚀

**Comment by spapas** [comment]
Hey @treyhunner unfortunately I can't merge this PR, it won't allow me until all checks have passed! So I guess we've got a chicken and egg problem :) 

I think that you as a superuser should be able to bypass the checks and merge this ?

**Comment by treyhunner** [comment]
Merged. Let's hope it passes! 🤞

**Pull request merged**
