### PR TITLE
Feature/django 3.0 support

### PR DESCRIPTION
**Pull request by BeOleg**
enabling this package to run with Django 3.0

### CODE REVIEW

**Comment by BeOleg** [comment]
https://github.com/treyhunner/django-email-log/issues/18

**Comment by bittner** [comment]
Could you update the test matrix ([tox](https://github.com/treyhunner/django-email-log/blob/master/tox.ini#L3-L6), [travis](https://github.com/treyhunner/django-email-log/blob/master/.travis.yml)) and make the build pass? That would be awesome!

Everything else than what is officially supported is probably unnecessary to include in the build matrix. You may want to get inspired by, e.g., [behave-django](https://github.com/behave/behave-django) (tox.ini, .travis.yml) for that.

**Comment by BeOleg** [comment]
@bittner will do. was going to do that earlier if I would get any feedback. just made the WIP PR to see if this project is still alive :)

**Comment by autoferrit** [comment]
Any chance this could get fixed to be updated? we are hitting this issue.

**Comment by treyhunner** [comment]
@BeOleg I've opened #20 as an alternative to this (the automated tests needed updating to support Django 3 as well)

I've just released django-email-log 1.0.0, based on that branch, which adds Django 3 support.

**Pull request closed without merging**
